### ISSUE TITLE
Bump `arkworks-rs` to `~0.4.0`

### ISSUE THREAD

**Issue by skaunov** [geometryresearch/ark-secp256k1#1]
Does this crate is planned to continue its journey, or maybe there is something else around for the purposes this crate was made back then?

PS I'm tackling <https://github.com/plume-sig/zk-nullifier-sig/issues/43>, and it [depends](https://github.com/plume-sig/zk-nullifier-sig/blob/42789dc9454c30549ec44e05e5470d77f645cdfe/rust-arkworks/Cargo.toml#L15) on this one. :face_with_spiral_eyes:

**Comment by weijiekoh** [comment]
Hi! This crate is unmaintained. Feel free to fork the repo and upgrade.

**Comment by skaunov** [comment]
Are you aware of any other places where this repo was used aside from <plume-sig/zk-nullifier-sig> repo?

**Comment by weijiekoh** [comment]
I'm not aware. This repo was only written with zk-nullifier-sig in mind.
